services:
  watch-next:
    container_name: watch-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/watch-next
    working_dir: /usr/src/watch-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# watch-next: localhost:4000 <=> container:3000
# watches_api: localhost:4001 <=> container:8000
# watches_batch: localhost:4002 <=> container:8001

# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && docker compose rm -f
